// react/src/containers/Login/index.js
import React, {useContext} from 'react';
import GoogleButton from 'react-google-button'
import FirebaseContext from '../../integrations/firebase/FirebaseContext';

/**
 * Render UI to display functionality for a user to log in to the application through google authentication.
 */
export default () => {
    const firebase = useContext(FirebaseContext);
    return (
        <div className="container d-flex mt-3 justify-content-center flex-column">
            <h1 className="text-center mb-1">Finder!</h1>
            <h5 className="text-center mb-5">Find a location and get directions to it.</h5>
            <div className="d-inline-flex justify-content-center">
                <GoogleButton onClick={firebase.googleSignIn}/>
            </div>
        </div>
    )
};

// vue/src/containers/Login.vue
<template>
    <div class="container d-flex mt-3 justify-content-center flex-column">
        <h1 class="text-center mb-1">Finder!</h1>
        <h5 class="text-center mb-5">Find a location and get directions to it.</h5>
        <div class="d-inline-flex justify-content-center">
            <button @click="$store.state.firebase.googleSignIn()">Sign In</button>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'Login',
    }
</script>
